agent:
  max_iterations: 5
  max_useful_chat_messages: 5 # Number of most recent/relevant messages to include as short-term memory
  save_session_trace: false

model:
  checkpoint: "qwen3.5:4b"
  context_window: 2048
  max_new_tokens: 1024
  think_mode: true

skills:
  skills_dir: "src/skills"

memory:
  memory_path: "memory/memory.db"
  checkpoint: "qwen3-embedding:0.6b"
  score_threshold: 0.25